### ISSUE TITLE
Failure in CoverageTest.bat

### ISSUE THREAD

**Issue by Kaviyesh** [TeledyneLeCroy/SignalIntegrity#24]
After installing PySI for developers, I ran the CoverageTest.bat.  I get two failures shown in the attached file.
![testfail](https://user-images.githubusercontent.com/16609237/46693029-bc74a100-cbd6-11e8-81db-6209daba098f.PNG)

**Comment by PetePupalaikis** [comment]
@Kaviyesh - can you check whether this is still a problem?  I think it's just a nuisance.  If it is, I will change the limit.

**Comment by Kaviyesh** [comment]
I installed the package on a new machine and tried the tests:
1. coverage was not present by default. I had to do a pip install coverage to run the bat file. Is this to be expected or would the installing of SI install coverage as well?
2. I see an u and some x's. Is this expected and would you want more details about it?
3. Seemed like it was stuck on a test for a long time - or atleast didn't seem to update the results. Seems like it is updating slowly. I now get different errors shown below:
![image](https://user-images.githubusercontent.com/16609237/92675915-81ada300-f2ee-11ea-9377-5fd9bf32670d.png)
H:\SignalIntegrity\Test>CoverageTest.bat
..............................................................................................................u...................................................................................................x........x.........................................................................................................................................................................................x.........................x...................................................................................................................E..E.......................................c:\hdrive\signalintegrity\SignalIntegrity\Lib\Fit\RLGC.py:245: ComplexWarning: Casting complex values to real discards the imaginary part
  dffmbdb=[ffmb*math.log(ffm+1e-15) for (ffmb,ffm) in zip(self.ffm,self.ffmb)]
................................................................................................................................................................................................................................x...........................................................................................................................................................................................................................................................................................................................................
======================================================================
ERROR: testNumericTwoPortParasiticCase0 (TestPI.TestPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\hdrive\signalintegrity\SignalIntegrity\Lib\SystemDescriptions\SystemSParametersNumeric.py", line 85, in SParameters
    result = array(Wba)+self.Dagger(I-array(Wxx),Left=Wbx,Right=Wxa,Mul=True)
  File "c:\hdrive\signalintegrity\SignalIntegrity\Lib\SystemDescriptions\Numeric.py", line 164, in Dagger
    raise LinAlgError
numpy.linalg.LinAlgError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\SignalIntegrity\Test\TestSignalIntegrity\TestPI.py", line 194, in testNumericTwoPortParasiticCase0
    spm=sspn.SParameters()
  File "c:\hdrive\signalintegrity\SignalIntegrity\Lib\SystemDescriptions\SystemSParametersNumeric.py", line 88, in SParameters
    raise SignalIntegrityExceptionNumeric('cannot invert I-Wxx')
SignalIntegrity.Lib.Exception.SignalIntegrityExceptionNumeric: Numeric

======================================================================
ERROR: testNumericTwoPortParasiticCase3 (TestPI.TestPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\hdrive\signalintegrity\SignalIntegrity\Lib\SystemDescriptions\SystemSParametersNumeric.py", line 85, in SParameters
    result = array(Wba)+self.Dagger(I-array(Wxx),Left=Wbx,Right=Wxa,Mul=True)
  File "c:\hdrive\signalintegrity\SignalIntegrity\Lib\SystemDescriptions\Numeric.py", line 164, in Dagger
    raise LinAlgError
numpy.linalg.LinAlgError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\SignalIntegrity\Test\TestSignalIntegrity\TestPI.py", line 299, in testNumericTwoPortParasiticCase3
    spm=sspn.SParameters()
  File "c:\hdrive\signalintegrity\SignalIntegrity\Lib\SystemDescriptions\SystemSParametersNumeric.py", line 88, in SParameters
    raise SignalIntegrityExceptionNumeric('cannot invert I-Wxx')
SignalIntegrity.Lib.Exception.SignalIntegrityExceptionNumeric: Numeric

----------------------------------------------------------------------
Ran 1146 tests in 4610.562s

FAILED (errors=2, expected failures=5, unexpected successes=1)
Press any key to continue . . .
Press any key to continue . . .

**Comment by Kaviyesh** [comment]
Ran the tests again after setting the preferences. I get the following error - not sure if this is a concern:
![image](https://user-images.githubusercontent.com/16609237/92929660-e8c27900-f40e-11ea-9d70-c9021e75b925.png)

**Comment by PetePupalaikis** [comment]
@Kaviyesh @anirudhsureka I think I've now fixed things so your tests should pass.  I also made the test passage impervious to your settings of UseSinX and TrySVD, which I usually have as True in my preferences.
It's on the InNextRelease branch -- try it and let me know.
