### ISSUE TITLE
Error (?) in book on page 15

### ISSUE THREAD

**Issue by mikefredd** [TeledyneLeCroy/SignalIntegrity#41]
[Y] matrix in book at top of the page 15 is defined as [Z]?

Best Regards,

Mike

**Comment by PetePupalaikis** [comment]
Yes -- you are correct.  A colleague of mine had already pointed this out.  There are (unfortunately) a few more of these.  I didn't expect people to have these books and actually be reading this yet.  I guess I better get to work updating the errata.  (the site for that is on page 591).

Thank you for sending this.

Pete

**Comment by PetePupalaikis** [comment]
While not technically resolved, I did enter this on the errata page for the book.

I'll close this issue based on that.
