### ISSUE TITLE
New User Install Help? :)

### ISSUE THREAD

**Issue by westec2** [TeledyneLeCroy/SignalIntegrity#49]
Did I do something wrong in the install?  Thanks!!!

C:\Users\xx\Documents\software\Lecroy_SignalIntegrity\SignalIntegrity-1.1.9>python setup.py develop
C:\Program Files\Python35\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
C:\Program Files\Python35\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running develop
running egg_info
writing SignalIntegrity.egg-info\PKG-INFO
writing requirements to SignalIntegrity.egg-info\requires.txt
writing entry points to SignalIntegrity.egg-info\entry_points.txt
writing dependency_links to SignalIntegrity.egg-info\dependency_links.txt
writing top-level names to SignalIntegrity.egg-info\top_level.txt
reading manifest file 'SignalIntegrity.egg-info\SOURCES.txt'
writing manifest file 'SignalIntegrity.egg-info\SOURCES.txt'
running build_ext
Creating c:\program files\python35\lib\site-packages\SignalIntegrity.egg-link (link to .)
SignalIntegrity 1.1.9 is already the active version in easy-install.pth
Installing SignalIntegrity-script.py script to C:\Program Files\Python35\Scripts
Installing SignalIntegrity.exe script to C:\Program Files\Python35\Scripts

From an admin command prompt:
Installed c:\users\xx\documents\software\lecroy_signalintegrity\signalintegrity-1.1.9
Processing dependencies for SignalIntegrity==1.1.9
Searching for urllib3>=1.22.0
Reading https://pypi.python.org/simple/urllib3/
Download error on https://pypi.python.org/simple/urllib3/: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions -- Some packages may not be found!
Couldn't find index page for 'urllib3' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions -- Some packages may not be found!
No local packages or download links found for urllib3>=1.22.0
error: Could not find suitable distribution for Requirement.parse('urllib3>=1.22.0')

**Comment by PetePupalaikis** [comment]
If you read these error messages, you are having a problem with python accessing a socket.  See:

https://stackoverflow.com/questions/2778840/socket-error-errno-10013-an-attempt-was-made-to-access-a-socket-in-a-way-forb

try installing the dependent packages yourself.  Fortunately, SignalIntegrity depends on only a few packages.  These are:

matplotlib, urllib3, numpy

If you can't install these yourself, then I don't know what I can do for you.  It's not a problem with this installer.

**Comment by PetePupalaikis** [comment]
Did you manage to get this working?  Can I close this issue?

**Comment by westec2** [comment]
Hi Pete,

I gave up… go ahead and close it.  I’ll just blame it on Lockheed lol

Thanks,
Joseph

**Comment by PetePupalaikis** [comment]
That's a shame.  If you want, I could try to look at things and try to set it up through a skype call, if you want.  If not, I will close it then.

**Comment by westec2** [comment]
Yah I was really bummed out.  Since you’re offering, I’ll put it another request to extend the eval (I have to get new admin rights, so it could take a while to get the approval.)

Thanks!

**Comment by PetePupalaikis** [comment]
Yes - get yourself and your machine in a state to try this again and then we can set up a Skype call.  
The SignalIntegrity software depends on only a few other Python packages and they are very standard, being: numpy, matplotlib, and urllib3.  It looks like during the install, it is trying to get those and failing - because of something to do with your machines ability to access the internet.  To test this, you can try installing these packages separately, like:
    pip install numpy
    pip install matplotlib
    pip install urllib3
If you can't do that successfully, then I wouldn't know what to say, and it certainly would point to another issue than my installer.  Either way, I like to resolve these so I can put the information on how to debug these problems on my documentation pages.

**Comment by westec2** [comment]
Uh oh.. here’s what I get:

C:\inst>pip install numby
Collecting numby
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002B4F80E5908>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/numby/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002B4F80E5A90>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/numby/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002B4F80E5BE0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/numby/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002B4F80E5D30>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/numby/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002B4F80E5E80>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/numby/
  Could not find a version that satisfies the requirement numby (from versions: )
No matching distribution found for numby

**Comment by PetePupalaikis** [comment]
It's numpy not numby

**Comment by westec2** [comment]
Same thing lol…. Is it possible to download the installer and install it manually?  Thanks!

C:\inst>pip install numpy
Collecting numpy
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002626AAB5898>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/numpy/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002626AAB5A20>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/numpy/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002626AAB5B70>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/numpy/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002626AAB5CC0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/numpy/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002626AAB5E10>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/numpy/
  Could not find a version that satisfies the requirement numpy (from versions: )
No matching distribution found for numpy

C:\inst>pip install numpy
Collecting numpy
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000268058256D8>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions',)': /simple/numpy/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000026805825A20>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions',)': /simple/numpy/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000026805825B70>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions',)': /simple/numpy/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000026805825CC0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions',)': /simple/numpy/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000026805825E10>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions',)': /simple/numpy/
  Could not find a version that satisfies the requirement numpy (from versions: )
No matching distribution found for numpy

C:\inst>ping ibm.com

Pinging ibm.com [129.42.38.10] with 32 bytes of data:
Reply from 129.42.38.10: bytes=32 time=55ms TTL=51
Reply from 129.42.38.10: bytes=32 time=57ms TTL=51
Reply from 129.42.38.10: bytes=32 time=84ms TTL=51
Reply from 129.42.38.10: bytes=32 time=46ms TTL=51

Ping statistics for 129.42.38.10:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 46ms, Maximum = 84ms, Average = 60ms

**Comment by PetePupalaikis** [comment]
I did some research on this problem.  I found numerous posts about this type of error.  I can see no clear conclusion.  Theories are: administrative rights, firewalls, antivirus software, used sockets, etc. etc.
You can get the software and install each piece yourself.  You'd do this by visiting:
    https://pypi.org/project/numpy/
    https://pypi.org/project/urllib3/
    https://pypi.org/project/matplotlib/

I don't think I can help you anymore -- it's something else about your computer environment.

**Comment by PetePupalaikis** [comment]
Sorry I couldn't help you.
