### ISSUE TITLE
branch changes does not exist

### ISSUE THREAD

**Issue by kmrb** [TeledyneLeCroy/SignalIntegrity#50]
Hi Pete

https://github.com/TeledyneLeCroy/SignalIntegrity/wiki/Developers

git init
git remote add origin https://github.com/TeledyneLeCroy/SignalIntegrity.git
git pull origin changes
....
changes - where all derived branches for code development should be made from.

This branch currently does not exist and causes git pull command to fail.

Keith R

**Comment by PetePupalaikis** [comment]
Hi Keith:

Thanks for keeping me on my toes.  I need to update that.

do:

    git pull origin InNextRelease

I renamed the branch that has code to be released.  I'm going to change it yet again in the future to 'beta', with the implication that master is the release branch and pulling beta will pull things that are planned (so you could beta test them).

I would also do:

    git fetch origin

Then it gets all branches onto your local machine.

Pete
________________________________

**Comment by PetePupalaikis** [comment]
I did just now update the documentation on the website.  Let me know how it looks and whether I can close this.

**Comment by kmrb** [comment]
Issue resolved 
your changes make sense
thx
