### ISSUE TITLE
bbm.sty dependency in LaTeX for matrix output

### ISSUE THREAD

**Issue by kmrb** [TeledyneLeCroy/SignalIntegrity#51]
Hi Pete

I wrote a short python script based on an example in the SI book (attached below) which in the end I could convert to a PDF and view the expected output.  I noticed the LaTeX created includes  "\mathbbm{I}" . This seems to require the bbm.sty file in Texlive.  This is unfortunately not supported by the RHEL7/CENTOS7 rpm versions of texlive (it was in older versions with and extension package that isn't available for this Linux version).  I believe for RHEL8/CENTOS8 there may be a compatible fedora rpm that provides bbm.sty but unfortunately this is packaged in a way not acceptable to CENTOS7.

To work around this I installed a 2020 (latest) texlive standalone installation (ie outside of rpm) to give me a pdflatex install that included bbm.sty.  In general on a shared CAD linux system this approach is not great.

After doing this, I still had to modify the docstart parameter when initializing SystemSParametersSymbolic class to include a usepackage{bbm} to get pdflatex  to correctly load the package.

Q1 : As far as docstart should bbm be included in the default ?

Q2 : To be compatible with the standard RHEL7/CENTOS7 installs (not uncommon among CAD software users) it might be nice to make the dependency on bbm optional.  

Keith

import SignalIntegrity.Lib as si
sdp=si.p.SystemDescriptionParser()
sdp.AddLines(['device DV 4','device ZI 2','device ZO 2','connect ZI 1 DV 2',
    'connect ZI 2 DV 1','connect ZO 1 DV 4','port 1 ZI 1 2 ZI 2 3 ZO 2 4 DV 3'])
ssps=si.sd.SystemSParametersSymbolic(sdp.SystemDescription(),size='small',
	docstart="""\\documentclass[10pt]{article}
\\usepackage{amsmath}
\\usepackage{bbm}
\\usepackage{bbold}
\\begin{document}
"""
)
ssps.AssignSParameters('DV',si.sy.VoltageControlledVoltageSource('\\alpha'))
ssps.AssignSParameters('ZI',si.sy.SeriesZ('Z_i'))
ssps.AssignSParameters('ZO',si.sy.SeriesZ('Z_o'))
ssps.DocStart()
ssps.LaTeXSolution(size='big',solvetype='direct')
ssps.DocEnd()
ssps.Emit()

**Comment by kmrb** [comment]
There seems to be a possible solution  in the accepted answer for the following stack exchange question that locally defines mathbbm if you that is the only part of bbm required.  I appreciate cut and pasting from the internals of external packages is a hack.

https://tex.stackexchange.com/questions/88734/mathbbm1-not-working-well-with-xelatex-mathspec

**Comment by PetePupalaikis** [comment]
There are multiple answers to this question:

1. bbm ought to be installed or installable.  In texlive it's in texlive-fonts-extra package in Debian.  I know the guy who packages this for Debian and asked him and he says that would be bug if it's missing.  He said to try:
     dnf search bbm
and see what happens.  On Ubuntu, I use Synaptic to view the packages - I don't know what you use, and when I search bbm, it does take me to the texlive-fonts-extra package (mine is 2019.202000218-1 (focal)).

2. bbm is used to define the identity matrix, which is specially defined as:
you could define \mathbbm to nothing, if you wanted. Or better yet, define \mathbbm to produce \mathbf\mathrm which would give you a bold, upright I.  I avoid that throughout my book as it would preclude matrices of current, which as you know, would be a shame for us electrical engineers.

3. The docstart string is meant for you to rewrite if you don't like it, as you did.  It was meant to be an argument to the constructor for this purpose.  I know you might not love that answer, as it takes more LaTeX knowledge, but I think your problems with the bbm package seem unusual to me. (You would say everyone using Red Hat / CentOS will have this problem).

**Comment by PetePupalaikis** [comment]
> There seems to be a possible solution in the accepted answer for the following stack exchange question that locally defines mathbbm if you that is the only part of bbm required. I appreciate cut and pasting from the internals of external packages is a hack.
> 
> https://tex.stackexchange.com/questions/88734/mathbbm1-not-working-well-with-xelatex-mathspec

are you using xelatex?  I would use pdflatex or even better, lualatex.  xelatex is needed to render windows fonts, but things don't look as good that way.

**Comment by kmrb** [comment]
I am using pdflatex.  The link was the result of wider searching trying to find a way of avoiding the missing package in Redhat packaging.  I'm pretty confident that bbm.sty is not available via the standard Redhat/EPEL packaging system for RHEL 7.  In Fedora packaging (which may be compatible with Redhat 8.1) there is a package texlive-bbmmacros but unfortunately it includes a more recent packaging mechanism that prevents a RHEL 7 install.

a) I found a several bugs filed against Redhat releases for these types of LaTeX files and it doesn't sound likely this will be resolved for RHEL7.  
b) As you say a Centos/RHEL user could do a local redefine added to the docstart parameter with a local definition to avoid the dependency.
c) A standalone non packaged 2020 texlive install works fine with SignalIntegrity.  The default installer seems to keep it separate as a "local" package that keeps it separate from the redhat managed files. Not ideal but definitely workable.

I will change default docstart parameter to include bbm, in all cases where output will include Identity matrix to avoid pdflatex failing.

As there are multiple ways around this I will close this.  Hopefully this problem will disappear as RHEL8/Centos8 is deployed.

**Comment by PetePupalaikis** [comment]
Thanks Keith,
On a side note, having Texlive installed they way you managed used to be the ONLY viable solution, as the version managed by the package manager used to be woefully out of date.  This caused other maintenance issues (I remember I had to have both side by side to satisfy various package manager dependencies -- ugh).  Now, for Ubuntu, this is in very good shape.
