### ISSUE TITLE
Namespace doesn't match doxygen documentation

### ISSUE THREAD

**Issue by barnetto** [TeledyneLeCroy/SignalIntegrity#53]
http://teledynelecroy.github.io/SignalIntegrity/Doc/xhtml/index.xhtml has si.d as namespace for Devices but __init__.py has "from . import Devices as dev"
  si.d.MixedModeConverter()
does not work but
  si.dev.MixedModeConverter()
does work.

**Comment by PetePupalaikis** [comment]
you're right - will be fixed in next release - thanks.
