### ISSUE TITLE
can i generate a eye diagram using this software

### ISSUE THREAD

**Issue by shushilcool** [TeledyneLeCroy/SignalIntegrity#54]
good regards,
can i know if i can use this software for generating the eye diagram for the s2p files and s4p files which are generated by openEMS

**Comment by PetePupalaikis** [comment]
I currently generate eye diagrams with this software, but in a separate script.  The software to do that is not currently part of this package.  It's probably the next thing it needs.

Something like this:
![Eye](https://user-images.githubusercontent.com/16583311/95660418-c5feaf80-0af5-11eb-930e-1d5063e7c6f7.png)
