### ISSUE TITLE
Time Gating and Impedance Peeling

### ISSUE THREAD

**Issue by EdgarMerger** [TeledyneLeCroy/SignalIntegrity#58]
Hi Pete, 

I do love the De-Embedding feature. I would love even more a Time Gating feature. Is that something you could add in the future? 
What I am looking for is a way to de-embed S-Parameters from fixtures that are present in the measured S-Parameters. I would like to remove that from the impedance profile. 
Might there be a trick to do so already?

Best regards,
Edgar

**Comment by EdgarMerger** [comment]
I have found an example in one of your papers. Very helpful. In principle I understood it. One would take time- points in impedance profile from the area where the adapter it's impedance profile is, use the Impedances at this points and built a cascaded T-Line structure with them. This cascade can then be de-embedded from the entire S-Parameter. Is that correct?
However these are many T-Lines to do that by hand and place it in the schematic of SignalIntegrity-App. Would have to look for automation possibilities in SignalIntegrity-Lib. 
WavePulser its Software obviously does that.

**Comment by PetePupalaikis** [comment]
Hi Edgar:

Yes, there is a way to do this already. You'll notice that when you place a port, there is a time delay value in its properties.  If you view the impedance profile of your s-parameters and identify the amount of time you'd like to peel off, you can enter this amount of time in the port, and the result has that amount of time peeled off using the impedance profile.

See: file:///home/petep/Work/SignalIntegrity/SignalIntegrity/App/Help/Help.html.LyXconv/Help-Subsection-77.html#device:Port

Pete

**Comment by EdgarMerger** [comment]
Hi Pete,

cool. Thanks. 

Edgar
