### ISSUE TITLE
Incorrect documentation of offset loss unit for Open/Short/Load Standards

### ISSUE THREAD

**Issue by biergaizi** [TeledyneLeCroy/SignalIntegrity#65]
The documentation of `offsetLoss` in `OpenStandard`, `ShortStandard` and `LoadStandard` appears incorrect. It reads:

> offsetLoss (optional) float loss due to skin-effect defined in **Gohms/s** at f0 (defaults to 0).

However, all of these classes actually pass the `offsetLoss` unchanged into the `Offset` class.

    class OpenStandard(SParameters):
        """class providing the s-parameters of an open standard as commonly defined
        for a calibration kit."""
        def __init__(self,f,offsetDelay=0.0,offsetZ0=50.0,offsetLoss=0.0,f0=1e9,
                     C0=0.0,C1=0.0,C2=0.0,C3=0.0):
            # [...]
            offsetSParameters=Offset(f,offsetDelay,offsetZ0,offsetLoss,f0)

And the `Offset` class actually interprets `offsetLoss` in **ohms/s**, not **Gohms/s**.

> offsetLoss (optional) float loss due to skin-effect defined in **ohms/s** at f0 (defaults to 0).

Due to this typo, I've wasted hours trying to solve my incorrect calculations in SignalIntegrity, it was because `offsetLoss` didn't do anything - it was too small by 9 orders of magnitude.

I've opened Pull Request #64 with a patch to solve this problem.

**Comment by PetePupalaikis** [comment]
resolved in release 1.3.0
